import { useState } from "react";
import { Link } from "wouter";
import { CheckCircle2, AlertTriangle, Clock, FileText, ArrowRight, ChevronDown, ChevronUp } from "lucide-react";
import PublicLayout from "@/components/PublicLayout";
import { useSeo } from "@/hooks/use-seo";

const howToSchema = {
  "@context": "https://schema.org",
  "@type": "HowTo",
  name: "How to Carry Out a Right to Rent Check in the UK",
  description:
    "A step-by-step guide for landlords and letting agents on conducting a Right to Rent check in compliance with the Immigration Act 2014.",
  step: [
    {
      "@type": "HowToStep",
      position: 1,
      name: "Request documents before tenancy starts",
      text: "Before the tenancy begins, ask every adult occupant (18+) for their Right to Rent documents. You cannot start the tenancy until the check is completed.",
    },
    {
      "@type": "HowToStep",
      position: 2,
      name: "Verify documents in person or via online share code",
      text: "For physical documents: check them in person with the tenant present, or use a certified Identity Verification Technology (IDVT) service. For digital status: ask the tenant for their share code and check it at gov.uk/view-right-to-rent.",
    },
    {
      "@type": "HowToStep",
      position: 3,
      name: "Determine whether the right to rent is time-limited",
      text: "List A documents (e.g. UK passport, settled status) confer an unlimited right to rent — no follow-up check needed. List B documents (e.g. pre-settled status, visa with expiry) are time-limited — you must re-check before expiry.",
    },
    {
      "@type": "HowToStep",
      position: 4,
      name: "Retain copies for your records",
      text: "Make a copy (or screenshot) of the documents or share-code confirmation. Date-stamp it. Retain this for the duration of the tenancy plus one year.",
    },
    {
      "@type": "HowToStep",
      position: 5,
      name: "Diarise follow-up checks for time-limited right to rent",
      text: "For List B occupants, set a reminder to re-check their status before the earlier of: the date on their current leave, or 12 months from your last check.",
    },
  ],
};

const articleSchema = {
  "@context": "https://schema.org",
  "@type": "Article",
  headline: "Right to Rent Check UK 2026: Complete Landlord Guide",
  datePublished: "2026-06-26",
  dateModified: "2026-06-26",
  author: { "@type": "Organization", name: "Elite Tenancy" },
  publisher: {
    "@type": "Organization",
    name: "Elite Tenancy",
    url: "https://www.elitetenancy.co.uk",
  },
  about: [
    {
      "@type": "Legislation",
      name: "Immigration Act 2014 — Right to Rent",
      jurisdiction: "England",
    },
    {
      "@type": "Legislation",
      name: "Immigration Act 2016 — Landlord Civil Penalties",
      jurisdiction: "England",
    },
  ],
};

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "What is a Right to Rent check?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "A Right to Rent check is a legal requirement under the Immigration Act 2014 for private landlords and letting agents in England. Before a tenancy begins, landlords must check that all adult occupants (aged 18+) have the legal right to rent in the UK, by inspecting their immigration documents or checking their online share code at gov.uk/view-right-to-rent.",
      },
    },
    {
      "@type": "Question",
      name: "Does Right to Rent apply in Scotland, Wales and Northern Ireland?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "No. Right to Rent is currently an England-only requirement under the Immigration Act 2014. Scotland, Wales, and Northern Ireland have different regulatory frameworks and are not subject to Right to Rent checks as of 2026.",
      },
    },
    {
      "@type": "Question",
      name: "What documents prove an unlimited right to rent?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "List A documents prove an unlimited right to rent and do not require a follow-up check. They include: a valid UK or Irish passport, a valid UK passport endorsed for indefinite leave to remain, a UK birth or adoption certificate plus an official letter showing a National Insurance number, a UK Biometric Residence Permit showing indefinite leave to remain or no time limit on stay, or a share code confirming Settled Status under the EU Settlement Scheme.",
      },
    },
    {
      "@type": "Question",
      name: "What is a Right to Rent share code?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "A share code is a 9-character alphanumeric code generated by the tenant at gov.uk/prove-right-to-rent. It gives the landlord a one-time view of the tenant's UK Visas and Immigration (UKVI) online profile — confirming their immigration status and any time limit on their right to rent. Share codes are used by EEA nationals with EU Settlement Scheme status, and by non-EEA nationals with digital immigration status.",
      },
    },
    {
      "@type": "Question",
      name: "How much is the civil penalty for not doing a Right to Rent check?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "If you rent to someone without the right to rent and cannot show you carried out a compliant check, the civil penalty is up to £20,000 per adult occupant for a first offence, and an unlimited penalty for a repeat offence. In the most serious cases — where a landlord knowingly rents to someone without leave to enter or remain — criminal prosecution is possible, carrying an unlimited fine or up to five years' imprisonment.",
      },
    },
    {
      "@type": "Question",
      name: "How long must I keep Right to Rent records?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "You must retain copies of Right to Rent documents (or share code confirmation screenshots) for the entire duration of the tenancy and for one year afterwards. Retain the date you made the copy, not just the document itself.",
      },
    },
    {
      "@type": "Question",
      name: "Does the Renters' Rights Act 2025 change Right to Rent rules?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "No. The Renters' Rights Act 2025 (which abolishes Section 21 notices and transitions all tenancies to periodic rolling tenancies) does not change the Right to Rent scheme. The requirements under the Immigration Act 2014 remain in force. Landlords must still carry out checks before the start of every tenancy, including on statutory periodic tenancies that arise after the RRA comes fully into effect.",
      },
    },
  ],
};

const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    {
      "@type": "ListItem",
      position: 1,
      name: "Home",
      item: "https://www.elitetenancy.co.uk/",
    },
    {
      "@type": "ListItem",
      position: 2,
      name: "Right to Rent Guide",
      item: "https://www.elitetenancy.co.uk/right-to-rent-guide",
    },
  ],
};

const LIST_A = [
  {
    doc: "Valid UK passport (any format)",
    notes: "Unlimited — no follow-up needed",
  },
  {
    doc: "Valid Irish passport or Irish passport card",
    notes: "Unlimited — no follow-up needed",
  },
  {
    doc: "UK Biometric Residence Permit — indefinite leave to remain",
    notes: "Unlimited — no follow-up needed",
  },
  {
    doc: "UK birth or adoption certificate + NI number letter",
    notes: "Unlimited — requires both documents together",
  },
  {
    doc: "Share code — EU Settlement Scheme Settled Status",
    notes: "Unlimited — confirm at gov.uk/view-right-to-rent",
  },
  {
    doc: "Certificate of naturalisation or registration as British citizen",
    notes: "Unlimited — no follow-up needed",
  },
];

const LIST_B = [
  {
    doc: "Valid passport with current leave vignette or digital status",
    notes: "Time-limited — follow up before expiry",
  },
  {
    doc: "UK Biometric Residence Permit — time-limited leave",
    notes: "Time-limited — follow up before expiry",
  },
  {
    doc: "Share code — EU Settlement Scheme Pre-Settled Status",
    notes: "5-year pre-settled leave — follow up before expiry",
  },
  {
    doc: "Home Office document confirming time-limited right to rent",
    notes: "Time-limited — follow up per letter date",
  },
];

const STEPS = [
  {
    n: "01",
    title: "Request documents before start of tenancy",
    body: "Every adult who will occupy the property (aged 18+) must be checked — including occupants not named on the tenancy agreement. Check before the tenancy begins.",
  },
  {
    n: "02",
    title: "Check documents are genuine",
    body: "For physical documents, check in person with the tenant present. Inspect photos, expiry dates, and security features. You may also use a certified Identity Document Validation Technology (IDVT) provider.",
  },
  {
    n: "03",
    title: "Verify online share codes",
    body: "Ask the tenant for their share code (generated at gov.uk/prove-right-to-rent). Check it yourself at gov.uk/view-right-to-rent — the result page confirms status and any expiry date.",
  },
  {
    n: "04",
    title: "Determine whether the right is time-limited",
    body: "List A = unlimited right to rent — no follow-up needed. List B = time-limited — diarise a re-check for before the earlier of expiry date or 12 months from today.",
  },
  {
    n: "05",
    title: "Retain copies for your records",
    body: "Take a copy of each document or screenshot the share code confirmation page. Note the date of check. Keep records for the length of the tenancy plus one year — these are your statutory excuse if challenged.",
  },
];

export default function RightToRentGuide() {
  useSeo({
    title:
      "Right to Rent Check UK 2026 — Complete Landlord Guide | Elite Tenancy",
    description:
      "Step-by-step Right to Rent guide for landlords. Accepted documents (List A & B), share codes, civil penalties up to £20,000, and record-keeping rules under the Immigration Act 2014.",
    canonical: "https://www.elitetenancy.co.uk/right-to-rent-guide",
  });

  const [openFaq, setOpenFaq] = useState<number | null>(null);

  return (
    <PublicLayout>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />

      {/* Hero */}
      <div className="bg-primary border-b border-accent/20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
          <nav className="text-xs text-muted-foreground mb-4 flex gap-1.5">
            <Link href="/" className="hover:text-accent transition-colors">
              Home
            </Link>
            <span>/</span>
            <span className="text-muted-foreground">Right to Rent Guide</span>
          </nav>
          <p className="text-accent text-xs font-semibold tracking-widest uppercase mb-3">
            Immigration Act 2014 — England
          </p>
          <h1 className="font-display text-4xl md:text-5xl font-semibold text-white tracking-tight mb-4 max-w-3xl">
            Right to Rent Check UK 2026
          </h1>
          <p className="text-lg text-muted-foreground max-w-2xl mb-8">
            Every private landlord in England must check that all adult
            occupants have the legal right to rent — before the tenancy starts.
            Here is exactly what to check, which documents to accept, and how
            to protect yourself from civil penalties.
          </p>
          <Link
            href="/right-to-rent-check"
            className="inline-flex items-center gap-2 bg-primary text-white px-6 py-3 rounded-lg font-semibold hover:bg-primary/90 transition-colors shadow-sm"
          >
            Run a Share Code Check <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="grid lg:grid-cols-3 gap-10">
          {/* Main content */}
          <div className="lg:col-span-2 space-y-12">

            {/* What is Right to Rent */}
            <section>
              <h2 className="font-display text-2xl font-semibold text-white tracking-tight mb-4">
                What is Right to Rent?
              </h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                Right to Rent is a legal duty introduced by the{" "}
                <strong>Immigration Act 2014</strong> and strengthened by the{" "}
                <strong>Immigration Act 2016</strong>. It applies to{" "}
                <em>all private landlords and their agents</em> letting
                residential property in England. Before a tenancy begins, you
                must check that every adult (18+) who will occupy the property
                has the right to reside in the UK — and therefore the right to
                rent.
              </p>
              <p className="text-muted-foreground leading-relaxed">
                Right to Rent does <strong>not</strong> apply in Scotland,
                Wales, or Northern Ireland. It covers all new tenancy agreements
                and renewals — including licences to occupy.
              </p>
            </section>

            {/* How to carry out a check */}
            <section>
              <h2 className="font-display text-2xl font-semibold text-white tracking-tight mb-6">
                How to carry out a Right to Rent check
              </h2>
              <div className="space-y-4">
                {STEPS.map((s) => (
                  <div
                    key={s.n}
                    className="flex gap-4 bg-white border border-border rounded-xl p-5 shadow-sm"
                  >
                    <div className="flex-shrink-0 w-10 h-10 rounded-full bg-accent/15 text-accent font-bold text-sm flex items-center justify-center">
                      {s.n}
                    </div>
                    <div>
                      <h3 className="font-semibold text-foreground mb-1">
                        {s.title}
                      </h3>
                      <p className="text-sm text-muted-foreground">{s.body}</p>
                    </div>
                  </div>
                ))}
              </div>
            </section>

            {/* Documents */}
            <section>
              <h2 className="font-display text-2xl font-semibold text-white tracking-tight mb-2">
                Accepted documents
              </h2>
              <p className="text-muted-foreground mb-6 text-sm">
                Documents fall into two lists. List A confers an{" "}
                <strong>unlimited</strong> right to rent — no follow-up check
                required. List B is <strong>time-limited</strong> — you must
                re-check before the leave expires.
              </p>

              <h3 className="text-lg font-semibold text-foreground mb-3 flex items-center gap-2">
                <span className="inline-flex items-center gap-1 bg-green-100 text-green-800 text-xs font-bold px-2.5 py-1 rounded-full">
                  <CheckCircle2 className="h-3.5 w-3.5" /> List A — Unlimited
                </span>
              </h3>
              <div className="overflow-hidden rounded-xl border border-border mb-8">
                <table className="w-full text-sm">
                  <thead className="bg-muted border-b border-border">
                    <tr>
                      <th className="text-left px-4 py-3 font-semibold text-foreground">
                        Document
                      </th>
                      <th className="text-left px-4 py-3 font-semibold text-foreground hidden sm:table-cell">
                        Notes
                      </th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-border/40">
                    {LIST_A.map((d, i) => (
                      <tr key={i} className="bg-white hover:bg-muted/50">
                        <td className="px-4 py-3 text-foreground">{d.doc}</td>
                        <td className="px-4 py-3 text-muted-foreground hidden sm:table-cell">
                          {d.notes}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              <h3 className="text-lg font-semibold text-foreground mb-3 flex items-center gap-2">
                <span className="inline-flex items-center gap-1 bg-accent/15 text-foreground text-xs font-bold px-2.5 py-1 rounded-full">
                  <Clock className="h-3.5 w-3.5" /> List B — Time-limited
                </span>
              </h3>
              <div className="overflow-hidden rounded-xl border border-border">
                <table className="w-full text-sm">
                  <thead className="bg-muted border-b border-border">
                    <tr>
                      <th className="text-left px-4 py-3 font-semibold text-foreground">
                        Document
                      </th>
                      <th className="text-left px-4 py-3 font-semibold text-foreground hidden sm:table-cell">
                        Notes
                      </th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-border/40">
                    {LIST_B.map((d, i) => (
                      <tr key={i} className="bg-white hover:bg-muted/50">
                        <td className="px-4 py-3 text-foreground">{d.doc}</td>
                        <td className="px-4 py-3 text-muted-foreground hidden sm:table-cell">
                          {d.notes}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </section>

            {/* Share codes */}
            <section>
              <h2 className="font-display text-2xl font-semibold text-white tracking-tight mb-4">
                Checking a share code
              </h2>
              <p className="text-muted-foreground mb-4 leading-relaxed">
                EEA nationals with EU Settlement Scheme status (and some
                non-EEA nationals with digital immigration status) no longer
                have a physical document. Instead, they generate a{" "}
                <strong>share code</strong> at{" "}
                <a
                  href="https://www.gov.uk/prove-right-to-rent"
                  rel="noopener noreferrer"
                  target="_blank"
                  className="text-accent underline hover:text-foreground"
                >
                  gov.uk/prove-right-to-rent
                </a>
                . The code is valid for 90 days.
              </p>
              <div className="bg-accent/10 border border-accent/20 rounded-xl p-5 space-y-3">
                <p className="text-sm font-semibold text-foreground">
                  To check a share code:
                </p>
                <ol className="text-sm text-foreground space-y-1.5 list-decimal list-inside">
                  <li>
                    Ask the tenant to generate their share code at
                    gov.uk/prove-right-to-rent.
                  </li>
                  <li>
                    Go to <strong>gov.uk/view-right-to-rent</strong> and enter
                    the share code and tenant's date of birth.
                  </li>
                  <li>
                    Confirm the tenant's identity by comparing their face to the
                    photo on screen.
                  </li>
                  <li>
                    Screenshot or print the result page and date-stamp it for
                    your records.
                  </li>
                </ol>
              </div>
            </section>

            {/* Civil penalties */}
            <section>
              <div className="bg-red-50 border border-red-200 rounded-xl p-6">
                <div className="flex items-start gap-3 mb-4">
                  <AlertTriangle className="h-5 w-5 text-red-600 flex-shrink-0 mt-0.5" />
                  <h2 className="font-display text-xl font-bold text-red-900">
                    Civil penalties for non-compliance
                  </h2>
                </div>
                <div className="grid sm:grid-cols-2 gap-4 mb-4">
                  <div className="bg-white rounded-lg border border-red-100 p-4 text-center">
                    <p className="text-3xl font-bold text-red-700 mb-1">
                      £20,000
                    </p>
                    <p className="text-sm text-red-800 font-semibold">
                      per occupant
                    </p>
                    <p className="text-xs text-red-600 mt-1">
                      First offence — no compliant check carried out
                    </p>
                  </div>
                  <div className="bg-white rounded-lg border border-red-100 p-4 text-center">
                    <p className="text-3xl font-bold text-red-700 mb-1">
                      Unlimited
                    </p>
                    <p className="text-sm text-red-800 font-semibold">
                      fine or prosecution
                    </p>
                    <p className="text-xs text-red-600 mt-1">
                      Repeat offence or knowingly renting unlawfully
                    </p>
                  </div>
                </div>
                <p className="text-xs text-red-700">
                  A compliant check (retained documents/screenshot, dated) gives
                  you a <em>statutory excuse</em> — meaning you cannot be
                  penalised even if the occupant had forged documents, provided
                  you checked in good faith and used reasonable skill.
                </p>
              </div>
            </section>

            {/* FAQs */}
            <section>
              <h2 className="font-display text-2xl font-semibold text-white tracking-tight mb-6">
                Common questions
              </h2>
              <div className="space-y-2">
                {faqSchema.mainEntity.map((faq, i) => (
                  <div
                    key={i}
                    className="bg-white border border-border rounded-xl overflow-hidden"
                  >
                    <button
                      className="w-full flex items-center justify-between px-5 py-4 text-left hover:bg-muted transition-colors"
                      onClick={() => setOpenFaq(openFaq === i ? null : i)}
                      aria-expanded={openFaq === i}
                    >
                      <span className="font-semibold text-foreground pr-4 text-sm">
                        {faq.name}
                      </span>
                      {openFaq === i ? (
                        <ChevronUp className="h-4 w-4 text-muted-foreground flex-shrink-0" />
                      ) : (
                        <ChevronDown className="h-4 w-4 text-muted-foreground flex-shrink-0" />
                      )}
                    </button>
                    {openFaq === i && (
                      <div className="px-5 pb-5 text-sm text-muted-foreground leading-relaxed border-t border-border/40">
                        <p className="pt-4">{faq.acceptedAnswer.text}</p>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </section>

          </div>

          {/* Sidebar */}
          <aside className="space-y-6">
            {/* Quick check CTA */}
            <div className="bg-accent/10 border border-accent/20 rounded-xl p-6 sticky top-6">
              <p className="text-xs font-semibold text-accent uppercase tracking-widest mb-2">
                Quick check
              </p>
              <h3 className="font-display text-lg font-semibold text-white tracking-tight mb-2">
                Check a share code now
              </h3>
              <p className="text-sm text-muted-foreground mb-4">
                Use Elite Tenancy's free Right to Rent share code checker —
                instant results with built-in reminder setting.
              </p>
              <Link
                href="/right-to-rent-check"
                className="w-full inline-flex items-center justify-center gap-2 bg-primary text-white px-4 py-3 rounded-lg font-semibold hover:bg-primary/90 transition-colors text-sm shadow-sm"
              >
                Check Share Code <ArrowRight className="h-4 w-4" />
              </Link>
            </div>

            {/* Key facts */}
            <div className="bg-white border border-border rounded-xl p-6 shadow-sm">
              <h3 className="font-semibold text-foreground mb-4 flex items-center gap-2">
                <FileText className="h-4 w-4 text-accent" /> Key facts at a
                glance
              </h3>
              <ul className="space-y-3 text-sm text-muted-foreground">
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="h-4 w-4 text-green-600 flex-shrink-0 mt-0.5" />
                  Applies to all private landlords in England
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="h-4 w-4 text-green-600 flex-shrink-0 mt-0.5" />
                  Check ALL adult occupants (18+)
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="h-4 w-4 text-green-600 flex-shrink-0 mt-0.5" />
                  Check before the tenancy starts
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="h-4 w-4 text-green-600 flex-shrink-0 mt-0.5" />
                  Keep records for tenancy + 1 year
                </li>
                <li className="flex items-start gap-2">
                  <Clock className="h-4 w-4 text-accent flex-shrink-0 mt-0.5" />
                  Re-check List B occupants before expiry
                </li>
                <li className="flex items-start gap-2">
                  <AlertTriangle className="h-4 w-4 text-red-500 flex-shrink-0 mt-0.5" />
                  Penalty up to £20,000 per occupant
                </li>
              </ul>
            </div>

            {/* RRA 2025 note */}
            <div className="bg-white border border-border rounded-xl p-6 shadow-sm">
              <h3 className="font-semibold text-foreground mb-2">
                RRA 2025 &amp; Right to Rent
              </h3>
              <p className="text-sm text-muted-foreground mb-3">
                The Renters' Rights Act 2025 abolishes Section 21 and changes
                tenancy structure — but it does <strong>not</strong> change
                Right to Rent rules.
              </p>
              <Link
                href="/renters-rights-act-2025"
                className="text-sm text-accent font-medium hover:text-foreground inline-flex items-center gap-1"
              >
                Full RRA 2025 guide <ArrowRight className="h-3.5 w-3.5" />
              </Link>
            </div>

            {/* Landlord CTA */}
            <div className="bg-primary rounded-xl p-6 text-white">
              <h3 className="font-display font-bold text-lg mb-2">
                Stress-free landlord?
              </h3>
              <p className="text-sm text-white/50 mb-4">
                Elite Tenancy handles Right to Rent checks, referencing, and
                tenant matching for you.
              </p>
              <Link
                href="/list-your-property"
                className="w-full inline-flex items-center justify-center gap-2 bg-accent text-white px-4 py-2.5 rounded-lg font-semibold hover:bg-accent transition-colors text-sm"
              >
                List Your Property <ArrowRight className="h-4 w-4" />
              </Link>
            </div>
          </aside>
        </div>
      </div>
    </PublicLayout>
  );
}
