import { Router, type IRouter } from "express";
import healthRouter from "./health";
import listingsRouter from "./listings";
import blogRouter from "./blog";
import contactRouter from "./contact";
import platformRouter from "./platform";
import landlordRouter from "./landlord";
import tenantRouter from "./tenant";
import adminRouter from "./admin";
import matchingRouter from "./matching";
import authRouter from "./auth";
import ellieRouter from "./ellie";
import whatsappRouter from "./whatsapp";
import messagesRouter from "./messages";
import paymentsRouter from "./payments";
import connectRouter from "./connect";
import subscriptionsRouter from "./subscriptions";
import n8nRouter from "./n8n";
import reviewsRouter from "./reviews";
import passportRouter from "./passport";
import verifyRouter from "./verify";
import rtrRouter from "./rtr";
import integrationsRouter from "./integrations";
import automationsRouter from "./automations";
import reputationRouter from "./reputation";
import referralsRouter from "./referrals";
// ── Module 2-4: Portal Architecture ──────────────────────────────────────────
import takeoverRouter from "./takeover";
import interestRouter from "./interest";
import { router as launchDiscountRouter } from "../services/launchDiscount";
import seedArticlesRouter from "./seedArticles";

const router: IRouter = Router();

router.use(authRouter);
router.use(ellieRouter);
router.use(whatsappRouter);
router.use(messagesRouter);
router.use(paymentsRouter);
router.use(connectRouter);
router.use(subscriptionsRouter);
router.use(n8nRouter);
router.use(reviewsRouter);
router.use(passportRouter);
router.use(verifyRouter);
router.use(rtrRouter);
router.use(automationsRouter);
router.use(reputationRouter);
router.use(referralsRouter);
router.use(integrationsRouter);
router.use(healthRouter);
router.use(listingsRouter);
router.use(blogRouter);
router.use(contactRouter);
router.use(platformRouter);
router.use(landlordRouter);
router.use(tenantRouter);
router.use(adminRouter);
router.use(matchingRouter);
// ── Portal Architecture routes ────────────────────────────────────────────────
router.use("/takeover",       takeoverRouter);
router.use("/interest",       interestRouter);
router.use("/launch-discount", launchDiscountRouter);
router.use(seedArticlesRouter);

export default router;
