/**
 * Elite Tenancy — WebSocket real-time messaging server
 *
 * Architecture:
 *  • One WS connection per authenticated user (replaces previous connection on reconnect)
 *  • Auth via short-lived token issued by GET /api/messages/ws-token
 *  • Messages stored in PostgreSQL; WS delivers them in real-time
 *  • Falls back gracefully: if recipient is offline, message is in DB for next poll
 *
 * Client message frames (JSON):
 *  { type: "ping" }
 *  { type: "send",  conversationId: number, content: string }
 *  { type: "read",  conversationId: number }
 *
 * Server message frames (JSON):
 *  { type: "pong" }
 *  { type: "message",  message: MessageRow }
 *  { type: "read_ack", conversationId: number, byUserId: number }
 *  { type: "error",    message: string }
 */

import { WebSocketServer, WebSocket } from "ws";
import type { IncomingMessage, Server } from "http";
import { db, messagesTable, conversationsTable, usersTable } from "@workspace/db";
import { eq, and, or, isNull, ne } from "drizzle-orm";
import { logger } from "../lib/logger";
import { registerDispatcher } from "../lib/wsDispatch";
import crypto from "crypto";

// ── Token store for WS handshake auth ────────────────────────────────────────
// Tokens are single-use, 30-second TTL, generated by REST and consumed on connect

interface WsToken {
  userId: number;
  expires: number; // Date.now() + 30_000
}

export const wsTokenStore = new Map<string, WsToken>();

export function issueWsToken(userId: number): string {
  const token = crypto.randomBytes(32).toString("hex");
  wsTokenStore.set(token, { userId, expires: Date.now() + 30_000 });
  return token;
}

function consumeWsToken(token: string): number | null {
  const entry = wsTokenStore.get(token);
  wsTokenStore.delete(token);
  if (!entry) return null;
  if (Date.now() > entry.expires) return null;
  return entry.userId;
}

// ── WS rate limiter: max 60 "send" frames per user per minute ────────────────
// Uses a sliding-window counter reset. ping/read frames are exempt.
interface RateBucket { count: number; resetAt: number }
const wsRateLimiter = new Map<number, RateBucket>();

function checkSendRateLimit(userId: number): boolean {
  const now = Date.now();
  const bucket = wsRateLimiter.get(userId);

  if (!bucket || now > bucket.resetAt) {
    wsRateLimiter.set(userId, { count: 1, resetAt: now + 60_000 });
    return true;
  }

  if (bucket.count >= 60) {
    return false;
  }

  bucket.count += 1;
  return true;
}

// ── Connected clients map: userId → WebSocket ─────────────────────────────────
const clients = new Map<number, WebSocket>();

function send(ws: WebSocket, payload: unknown): void {
  if (ws.readyState === WebSocket.OPEN) {
    ws.send(JSON.stringify(payload));
  }
}

// ── Core message handler ──────────────────────────────────────────────────────
async function handleMessage(ws: WebSocket, userId: number, raw: string): Promise<void> {
  let frame: { type: string; conversationId?: number; content?: string };
  try {
    frame = JSON.parse(raw);
  } catch {
    send(ws, { type: "error", message: "Invalid JSON" });
    return;
  }

  if (frame.type === "ping") {
    send(ws, { type: "pong" });
    return;
  }

  if (frame.type === "send") {
    // Rate limit: 60 send frames per user per minute
    if (!checkSendRateLimit(userId)) {
      send(ws, { type: "error", message: "Rate limit exceeded — please slow down (60 messages/min)" });
      return;
    }

    const { conversationId, content } = frame;
    if (!conversationId || !content || typeof content !== "string") {
      send(ws, { type: "error", message: "conversationId and content required" });
      return;
    }
    if (content.trim().length === 0 || content.length > 4000) {
      send(ws, { type: "error", message: "Message must be 1–4000 characters" });
      return;
    }

    // Verify sender is a participant
    const [conv] = await db
      .select()
      .from(conversationsTable)
      .where(eq(conversationsTable.id, conversationId));

    if (!conv || (conv.landlordId !== userId && conv.tenantId !== userId)) {
      send(ws, { type: "error", message: "Not a participant in this conversation" });
      return;
    }

    // Persist to DB
    const [msg] = await db
      .insert(messagesTable)
      .values({ conversationId, senderId: userId, content: content.trim() })
      .returning();

    // Update conversation lastMessageAt
    await db
      .update(conversationsTable)
      .set({ lastMessageAt: new Date() })
      .where(eq(conversationsTable.id, conversationId));

    const outgoing = { type: "message", message: msg };

    // Deliver to both participants (sender gets echo, recipient gets push)
    const recipientId = conv.landlordId === userId ? conv.tenantId : conv.landlordId;
    const recipientWs = clients.get(recipientId);
    const senderWs = clients.get(userId);

    if (recipientWs) send(recipientWs, outgoing);
    if (senderWs) send(senderWs, outgoing);

    return;
  }

  if (frame.type === "read") {
    const { conversationId } = frame;
    if (!conversationId) {
      send(ws, { type: "error", message: "conversationId required" });
      return;
    }

    // Mark all messages in conversation not sent by this user as read
    // ne(senderId, userId) ensures we never mark the reader's own messages as read
    await db
      .update(messagesTable)
      .set({ readAt: new Date() })
      .where(
        and(
          eq(messagesTable.conversationId, conversationId),
          ne(messagesTable.senderId, userId),
          isNull(messagesTable.readAt),
        ),
      );

    // Notify the other participant their messages were read
    const [conv] = await db
      .select()
      .from(conversationsTable)
      .where(eq(conversationsTable.id, conversationId));

    if (conv) {
      const otherId = conv.landlordId === userId ? conv.tenantId : conv.landlordId;
      const otherWs = clients.get(otherId);
      if (otherWs) {
        send(otherWs, { type: "read_ack", conversationId, byUserId: userId });
      }
    }

    return;
  }

  send(ws, { type: "error", message: `Unknown message type: ${frame.type}` });
}

// ── WebSocket server setup ────────────────────────────────────────────────────
export function setupWebSocket(server: Server): void {
  const wss = new WebSocketServer({ server, path: "/ws" });

  wss.on("connection", async (ws: WebSocket, req: IncomingMessage) => {
    const url = new URL(req.url ?? "/", "http://localhost");
    const token = url.searchParams.get("token");

    if (!token) {
      ws.close(4001, "Missing token");
      return;
    }

    const userId = consumeWsToken(token);
    if (!userId) {
      ws.close(4001, "Invalid or expired token");
      return;
    }

    // Replace any existing connection for this user
    const existing = clients.get(userId);
    if (existing && existing.readyState === WebSocket.OPEN) {
      existing.close(4000, "Replaced by new connection");
    }
    clients.set(userId, ws);

    logger.info({ userId }, "WebSocket client connected");

    ws.on("message", (data) => {
      handleMessage(ws, userId, data.toString()).catch((err) => {
        logger.error({ err, userId }, "WS message handler error");
        send(ws, { type: "error", message: "Internal server error" });
      });
    });

    ws.on("close", () => {
      // Only remove if this is still the registered connection
      if (clients.get(userId) === ws) {
        clients.delete(userId);
        wsRateLimiter.delete(userId);
      }
      logger.info({ userId }, "WebSocket client disconnected");
    });

    ws.on("error", (err) => {
      logger.error({ err, userId }, "WebSocket error");
    });

    // Send connected acknowledgement
    send(ws, { type: "pong" });
  });

  // Prune expired tokens every minute
  setInterval(() => {
    const now = Date.now();
    for (const [key, val] of wsTokenStore) {
      if (now > val.expires) wsTokenStore.delete(key);
    }
  }, 60_000);

  // Register the internal dispatcher so routes can push frames to connected users
  registerDispatcher((userId: number, payload: unknown) => {
    const ws = clients.get(userId);
    if (ws && ws.readyState === WebSocket.OPEN) {
      ws.send(JSON.stringify(payload));
    }
  });

  logger.info("WebSocket server running on /ws");
}
